created forgot mail
rayonstudios/rayon_gcp_express_psql_starter pull request #3
Opened 2024-10-18 15:03 UTC by MuhammadUsama-hub

2024-10-18 20:09 UTC, MohammedMaaz requested changes
@MuhammadUsama-hub please apply the suggested changes. Also, please run `git pull origin main` in your current local branch once before doing any changes, to sync your branch with the latest code on main, since I have made some changes on main lately.

2024-10-18 20:09 UTC, MohammedMaaz commented on src/modules/auth/auth.controller.ts
> +  @Middlewares(validateData(authValidations.login.omit({ password: true })))
Don't do `omit`, create a separate validation schema for forgotPassword

2024-10-18 20:09 UTC, MohammedMaaz commented on src/modules/auth/auth.controller.ts
> +  //forgot password function
no need for this comment

2024-10-18 20:09 UTC, MohammedMaaz commented on src/modules/auth/auth.controller.ts
> +  ): Promise<APIResponse<string>> {
Instead of using raw strings in responses, let's use `{ message: "string"}` structure from now on. Please see example of this in `verifyEmail` function on `main` branch

2024-10-18 20:09 UTC, MohammedMaaz commented on src/modules/auth/auth.controller.ts
> +    }
We shouldn't do try/catch for individual controller functions as we already have a global error handler in place

2024-10-18 20:09 UTC, MohammedMaaz commented on src/modules/otp/otp.service.ts
> +      inviter: "jack", //feild not in db
Let's remove this field then

2024-10-18 20:09 UTC, MohammedMaaz commented on src/modules/otp/otp.types.ts
These types should go in `/mail/mail.types.ts` file, as they are relevant to mail templates

2024-10-18 20:09 UTC, MohammedMaaz commented on src/modules/otp/otp.types.ts
> +export type TemplateMethod = "verifyEmail" | "forgotPassword" | "createUser";
Define this as
```javascript
export type AuthTemplateType = keyof typeof sibTemplates.authentication;
```

2024-10-18 20:09 UTC, MohammedMaaz commented on src/modules/otp/otp.types.ts
> +export type TemplateParams =
Define this as
```javascript
export type AuthTemplateParams = Parameters<typeof sibTemplates.authentication[AuthTemplateType]>[0];
```

2024-10-18 20:09 UTC, MohammedMaaz commented on src/modules/auth/auth.controller.ts
> +      await otpService.send(user);
We should pass in the template type here as the 2nd argument

2024-10-18 20:09 UTC, MohammedMaaz commented on src/modules/auth/auth.controller.ts
> +      });
Once you have updated the response type to `Promise<APIResponse<Message>>`, this should become

```javascript
return toResponse({
  data:  { message: "Forgot password email send successfully" },
});
```

2024-10-19 07:19 UTC, MuhammadUsama-hub commented on src/modules/auth/auth.controller.ts
> +  @Middlewares(validateData(authValidations.login.omit({ password: true })))
done

2024-10-19 07:20 UTC, MuhammadUsama-hub commented on src/modules/auth/auth.controller.ts
> +  //forgot password function
done

2024-10-19 08:03 UTC, MuhammadUsama-hub commented on src/modules/auth/auth.controller.ts
> +  ): Promise<APIResponse<string>> {
done

2024-10-19 08:04 UTC, MuhammadUsama-hub commented on src/modules/auth/auth.controller.ts
> +    }
done

2024-10-19 08:13 UTC, MuhammadUsama-hub commented on src/modules/otp/otp.service.ts
> +      inviter: "jack", //feild not in db
done

2024-10-19 10:16 UTC, MuhammadUsama-hub commented
also check app.ts file as it show error that morgan module canot have or type declaration and also yarn not running show version issue .

2024-10-19 13:10 UTC, MohammedMaaz commented
> @MohammedMaaz also check app.ts file as it show error that morgan module canot have or type declaration and also yarn not running show version issue .

@MuhammadUsama-hub I have replaced yarn with npm, as Google App Engine was complaining. You should delete .yarn folder, yarn.lock file and any other yarn related files, and then run `npm install` once.

2024-10-20 18:52 UTC, MohammedMaaz approved these changes

2024-10-20 18:52 UTC, merged